---
abstract: 'is a TCP server that listens to messages from Jenkins Notification plugin.'
author:
  - 'Yo-An Lin <cornelius.howl {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jenkins-NotificationListener
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent::Socket: 0
  JSON: 0
  JSON::XS: 0
  Moose: 0
  Net::Jenkins: 0.03
  URI: 0
  YAML: 0
  methods: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
